import Image from 'next/image';
import styles from './page.module.scss';
const aboutMePage = () => {
  return (
    <div className={styles.wrapper}>
      <main className={styles.main}>
        <p>
          Im Piotrek i like coding, freestyle skiing, 3d modeling, riding on my
          bike and video games. The articles on this blog are generated by
          chatGPT but I{"'"}ll try to add my own content soon. 🫡
        </p>

        <div className={styles.image}>
          <Image
            src="https://avatars.githubusercontent.com/u/87661735?v=4"
            alt="github profile image"
            width={434}
            height={434}
          />
        </div>
      </main>
    </div>
  );
};

export default aboutMePage;
