#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "dev" ]; then
	echo "whatever branch is special, blabla..."
	npm run build

    nohup npm run start &

    npm run test
fi