#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
	echo "on main branch: building -> starting localhost -> e2e testing -> unit/integration testing -> pushing"
	npm run build

    nohup npm run start > /dev/null 2>&1 &

    npm run test
fi


if [ "$branch" = "dev" ]; then
	echo "on dev branch: building -> pushing"
	npm run build
fi